# Generated by Django 4.0.2 on 2022-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.TextField(max_length=4096)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
